### ISSUE TITLE
Possible performance degradation under Chrome Canary 61

### ISSUE THREAD

**Issue by bd82** [cdiggins/myna-parser#11]
Looks like Myna only runs much slower on Chrome Canary 61
(which includes the new TurboFan V8 compiler and Ignition interpreter).

I don't know if this is a bug in Chrome that will be fixed by the time an official version of Chrome is released or if it is a a real issue.

Just an heads up...

Also Note:
* Most other parsing libraries get a speed boost in Chrome Canary 61.
* Screen shot (I get about 500 ops/Second on Chrome 58)
![capture](https://cloud.githubusercontent.com/assets/4233843/26626198/2f119736-45ff-11e7-8807-baf520d29d81.PNG)

**Comment by cdiggins** [comment]
Thanks for letting me kno! Closing this issue, since there isn't much I can do about it now. I will be looking into the performance improvements suggested in #13 .

**Comment by bd82** [comment]
You can reproduce it now on latest Chrome stable version (59).
There is a new JavaScript optimizing compiler there (Ignition + turbofan)

I guess the new V8 is much slower for some code patterns used in Myna.
But I have no idea what / which / why.

Perhaps you need to compare CPU profiling results on different Chrome versions to figure this out.

Sounds like a pain 😢
