### ISSUE TITLE
Possible performance improvements 

### ISSUE THREAD

**Issue by bd82** [cdiggins/myna-parser#13]
### Class instances avoidance
I see much usage of the **new**keyword.

I am uncertain but it appears as though it may also be used in hot spots( parser runtime) in the code and not only in one time initial definitions?

if that is indeed the case I suggest you try avoiding initializing class instances at parser runtime. 
Plain objects ({}) if sufficient would be much faster.

### Specific boolean conditions.
This is a minor thing but conditions  such as:
```javascript
            if (!this.createsAstNode)
```

Will take longer than a more precise condition:
```
if (this.createsAstNode === false)
```

If these kind of conditions appear in enough hot spots in the code base
you may be able to squeeze a a tiny bit of extra performance.

**Comment by cdiggins** [comment]
![image](https://user-images.githubusercontent.com/1759994/27112896-b4348a80-5087-11e7-87c4-5db72da69eea.png)

**Comment by bd82** [comment]
Was this run on Chrome?
If so which version? 

I see a slightly different ordering on latest stable chrome **59**
