### ISSUE TITLE
2.4.0 no longer works in the browser.

### ISSUE THREAD

**Issue by bd82** [cdiggins/myna-parser#15]
Reproduce with this snippet:

```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

// will cause "Uncaught ReferenceError: exports is not defined"
<script src="https://unpkg.com/myna-parser/myna.js"></script>

</body>
</html>
```

Related to:
https://github.com/cdiggins/myna-parser/blob/master/myna.js#L1298

**Comment by cdiggins** [comment]
Thanks a lot for reporting this!! 
Fixed: https://cdiggins.github.io/myna-parser/tests/qunit.html

**Comment by bd82** [comment]
I think 2.4.2 is broken again while 2.4.1 works just fine.

**Comment by cdiggins** [comment]
For me it works here: https://cdiggins.github.io/myna-parser/tests/qunit.html any ideas?

**Comment by bd82** [comment]
Try to reproduce using the simplest of htmls:

```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

<script src="https://unpkg.com/myna-parser@2.4.2/myna.js"></script>

</body>
</html>
```

**Comment by bd82** [comment]
Using Myna with other TypeScript projects should not affect the need for runtime hacks.

For browser usage I suggest packaging with webpack using UMD module pattern.
That is how I package Chevrotain.
https://unpkg.com/chevrotain@1.0.1/lib/chevrotain.js

For using Myna with other TypeScript projects you only need to provide a d.ts file.
If you implement it using the ["export as namespace" ](https://github.com/Microsoft/TypeScript/wiki/What%27s-new-in-TypeScript#support-for-umd-module-definitions)

Consumers of Myna will be able to use it with any module system they are using in their tsconfig file.

**Comment by cdiggins** [comment]
@bd82 When learning TypeScript/JavaScript I initially was repulsed the idea of having to use a tool like webpack to deliver stuff to the web, but I think I will have to be more flexible on this. I appreciate your advice.

**Comment by bd82** [comment]
I just used the hack you suggested to update the benchmark page to 2.5.1 and it worked.
But not everyone can use that hack as 
```javascript
var exports = {}
```

is identical to 
```javascript
window.exports = {}
```

and may break popular libraries using the standard [UMD](https://github.com/umdjs/umd) pattern.
You may not need webpack, the TypeScript compiler can generate UMD code,
that may suffice for your simple scenario.
