### ISSUE TITLE
Case insensitive keywords?

### ISSUE THREAD

**Issue by Hypercubed** [cdiggins/myna-parser#16]
Should there be a way to declare a keyword (or char + seq) as case insensitive?

Something like:

```
this.exponent = m.seq(m.char("e").ignoreCase, this.plusOrMinus.opt, m.digits);

this.null = m.keyword("null").ignoreCase.ast;
```

**Comment by Hypercubed** [comment]
Maybe starting with something like:

```
class CaseInsensitiveCharSet extends m.CharSet {
    constructor(chars) {
        super([]);
        let vals = [];
        let length = chars.length;
        chars = chars.toLowerCase();
        for (var i=0; i < length; ++i)
          vals[i] = chars.charCodeAt(i);
        this.lexer = (p) => {
          let cc = p.input.charCodeAt(p.index);
          if (cc > 64 && cc < 91) {
            cc += 32;
          }
          return vals.indexOf(cc) >= 0
        }
        this.parser = this.lexer;
    }
}
```

and equivalent for `seq`?

**Comment by cdiggins** [comment]
This is a cool idea. I haven't needed it yet. Do you @Hypercubed? Only point is that the proposed fluent syntax wouldn't fit well, because it is not a general transform that can be applied to any rule (see: https://github.com/cdiggins/myna-parser/blob/master/myna.ts#L342).

**Comment by Hypercubed** [comment]
The `CaseInsensitiveCharSet` is not so useful... (`m.char("eE")` is easy enough).  I do need case insensitive keywords.   Do do this currently I'd need to define each variation:

```
m.keyword("null")
m.keyword("NULL")
m.keyword("Null")
m.keyword("NuLL")
...
```

**Comment by cdiggins** [comment]
Added in 2.4.3 see https://cdiggins.github.io/myna-parser/tests/qunit.html

**Comment by Hypercubed** [comment]
Very awesome... thank you!  I had to come back to this and contribute myself...   but time is finite.
